version: "3"
services:
  llava-python:
    build: .
    container_name: "llava-python"
    command: ["streamlit", "run", "app.py"]
    tty: true
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ".:/projects"
    working_dir: /projects
    ports:
      - 8501:8501
